GET http://localhost:3005/01HY73B00Y03K1VN3TT9DZR9JN
Accept: application/json

###
## Ge
POST http://localhost:3005//shorten
Content-Type: application/json

{
  "longUrl" : "https://awstip.com/unlocking-seamless-deployment-a-step-by-step-guide-to-deploy-code-on-amazon-ecs-fargate-new-ea391097fd96"
}
