GET http://localhost:3005/01HY87GQBFM4GM70MF7530EWZ0
Accept: application/json

###
###
POST http://localhost:3005//shorten
Content-Type: application/json

{
  "longUrl" : "https://www.jetbrains.com/rider/whatsnew/"
}
